# Generated by Django 6.0.6 on 2026-07-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_review_started_at_alter_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventevidence',
            name='document_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
