# Generated by Django 6.0.6 on 2026-07-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventevidence_document_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='permit_block_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='permit_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='permit_tx_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='permit_verified',
            field=models.BooleanField(default=False),
        ),
    ]
