# Generated by Django 6.0.6 on 2026-07-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified_user_verification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_document_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
