# Generated by Django 6.1.1 on 2026-10-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('restaurants', 'Restaurants'), ('snack', 'Snack'), ('drink', 'Drink')], max_length=20)),
                ('place', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_items/')),
                ('last_verified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_bundles/')),
                ('last_verified', models.DateField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='bundles', to='food.item')),
            ],
        ),
    ]
